# dummy language setting: ocaml
language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
#  - sudo apt-get -y install software-properties-common
#  - sudo add-apt-repository ppa:mc3man/trusty-media
#  - sudo apt-get update  
  - sudo apt install -y xvfb x11-apps imagemagick 

script:
  - eval $(opam env); make
  # dune
  - opam install dune
  # screenshot
  - "curl -L 'https://drive.google.com/uc?id=1Ej8VgsW5RgK66Btb9p74tSdHMH3p4UNb&export=download' > gdrive"
  - chmod +x gdrive

  - "curl -LO https://raw.githubusercontent.com/mamewotoko/xvfb-screenshooter/master/xvfb-screenshooter.sh"
  - chmod +x xvfb-screenshooter.sh
  - "./xvfb-screenshooter.sh timeout 10s dune exec src/main.exe &"
  - sh ci/upload.sh

env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
  # - osx
