# dummy language setting: ocaml
language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
  - sudo apt install -y xvfb
script:
  - eval $(opam env); make
  # dune
  - opam install dune
  - timeout 60s xvfb-run -a dune exec src/main.exe
  
env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
  # - osx
