# dummy language setting: ocaml
dist: xenial
sudo: required
addons:
  apt:
    sources:
      - ppa:mc3man/trusty-media
    packages:
      - xvfb
      - x11-apps
      - imagemagick
      - ffmpeg
install:
  - cat /etc/lsb-release
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
#  - sudo apt-get -y install software-properties-common
#  - sudo add-apt-repository 
#  - sudo apt-get update  
#  - sudo apt install -y xvfb x11-apps imagemagick ffmpeg

script:
  - eval $(opam env); make
  # dune
  - opam install dune
  # screenshot
  - "curl -fsSL https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64 > gdrive"
  - chmod +x gdrive

  - "curl -LO https://raw.githubusercontent.com/mamewotoko/xvfb-screenshooter/master/xvfb-screenshooter.sh"
  - chmod +x xvfb-screenshooter.sh
  - "./xvfb-screenshooter.sh timeout 10s dune exec src/main.exe"
  - sh ci/upload.sh

env:
  # - OCAML_VERSION=4.02
  # - OCAML_VERSION=4.03
  # - OCAML_VERSION=4.04
  # - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
  # - osx
